### PR TITLE
Make clone-ready

### PR DESCRIPTION
**Pull request by jacobscarfmerrell**

### CODE REVIEW

**Review by ngalter — APPROVED** [review]

**Comment by ngalter** [comment]
Hi Jacob,

Unless I am reading this wrong, I think we missed one name/keyword
combination.  I got an error this morning when I tried to run this.  It was
on line 25 in CreateButton/index.js

I'm not comfortable making the update.  I just cloned everything and
reinstalled.  There are some differences in my package.json.

Nancy

**Comment by ngalter** [comment]
Hi Jacob,

I worked on making some local updates to run the program.  I hit this
file-not-found error for aws-exports.js. I was able to locate it in
gitignore, so I see that I don't have it locally. Maybe you can send me the
code.
I will need it to run the program.

Thanks,

Nancy

**Comment by lydiascarf** [comment]
so we're not supposed to commit this for some reason. I'll try to figure
out how to avoid the issue, but put the following in the file and put the
file under src. I can do a quick call tomorrow if you want!

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS
Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id":
"us-east-1:b0cbe7fa-9ec0-42e6-8fbb-1b3a71cc15d8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rPxWRV7bP",
    "aws_user_pools_web_client_id": "1gijuk82a17qda5cn93ihqga26",
    "oauth": {},
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "
https://jtcvaxpfpzcixgptlzdan35p7m.appsync-api.us-east-1.amazonaws.com/graphql
",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "
https://igkpehl3la.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;

**Comment by ngalter** [comment]
thanks.  I'll give it a try

Nancy

**Comment by ngalter** [comment]
I got in!  So I'm on to the next step of seeing how to pass the data in and
out.

Thanks,

Nancy

**Pull request merged**
